import { StyleSheet } from 'react-native';
import Colors from '../../utills/Colors';
import { width, height, totalSize } from 'react-native-dimension';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.backgroundColor,
    justifyContent: 'space-between',
  },
  headerContainer: {
    width: width(100),
    paddingHorizontal: width(5),
    alignSelf: 'center',
    backgroundColor: Colors.backgroundWhite,
  },
  headerTitle: {
    color: Colors.textBlack,
  },
  scroll: {
    // height: height(80),
  },
  backIcon: {
    tintColor: Colors.grayDarker,
  },
  backIconContainerStyle: {
    backgroundColor: 'rgba(243,244,245,1)',
  },
  innerContainer: {
    backgroundColor: Colors.backgroundColor,
    width: width(100),
    marginTop: height(12),
    borderTopLeftRadius: width(9),
    borderTopRightRadius: width(9),
    paddingBottom: height(1),
    overflow: 'visible',
  },
  lineSeparator: {
    height: 0.5,
    backgroundColor: Colors.placeHolderTextColor,
    width: '100%',
    marginVertical: height(1),
  },
  button: {
    backgroundColor: Colors.buttonBlue,
    marginTop: 0,
    height: height(7),
    borderColor: Colors.buttonBlue,
    shadowColor: Colors.buttonBlue,
    marginTop:height(6)
  },
  buttonText: {
    fontWeight: 'bold',
    fontSize: width(4.5),
  },
  approvedOrdersContainer: {
    backgroundColor: Colors.backgroundWhite,
    width: width(90),
    alignSelf: 'center',
    paddingVertical: height(1.5),
    borderRadius: width(4),
    top: height(11),
  },
  approverImageContainer: {
    width: width(90),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: height(2.5),
    paddingHorizontal: width(5),
    backgroundColor: Colors.backgroundWhite,
    paddingVertical: height(2.5),
    borderRadius: width(4),
  },
  approverImage: {
    height: height(8),
    width: height(8),
    borderRadius: width(4),
  },
  approverNameContainer: {
    width: width(60),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  approverName: {
    fontWeight: 'bold',
    fontSize: width(4),
    color: Colors.textBlack,
  },
  orderIdTextName: {
    fontSize: width(2.9),
    color: Colors.buttonBlue,
  },
  oridText: {
    color: Colors.gray,
    fontSize: width(2.7),
  },
  buttonContainer: {
    flexDirection: 'row',
  },
  phoneButtonContainer: {
    height: totalSize(4.5),
    width: totalSize(4.5),
    borderRadius: totalSize(2.5),
    backgroundColor: Colors.opacitiveBlue,
    marginHorizontal: width(2),
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatButtonContainer: {
    height: totalSize(4.5),
    width: totalSize(4.5),
    borderRadius: totalSize(2.5),
    backgroundColor: Colors.opacitiveBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatImage: {
    height: height(2.25),
    width: height(2.25),
  },
  dateDeliveryContainer: {
    width: width(80),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: height(1),
  },
  dateDeliveryhoursContainer: {
    width: width(80),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: height(0.5),
  },
  dateDeliveryText: {
    color: Colors.gray,
    fontSize: width(3),
  },
  dateDeliveryTimeText: {
    fontWeight: 'bold',
    fontSize: width(3.25),
    color: Colors.textBlack,
  },
  timeLeftText: {
    color: Colors.purplePrimary,
    fontSize: width(3.25),
  },
  itemsDetailContainer: {
    width: width(90),
    borderRadius: width(4),
    backgroundColor: Colors.backgroundWhite,
    alignSelf: 'center',
    paddingBottom: height(2),
  },
  itemContainer: {
    width: width(83),
    alignSelf: 'center',
    // flexDirection: "row",
    marginTop: height(2),
  },
  itemImage: {
    height: height(8),
    width: height(7.5),
    borderRadius: width(2),
  },
  imageMainContainer: {
    width: width(65),
    marginLeft: width(3),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  shopName: {
    color: Colors.textBlack,
    fontWeight: 'bold',
    fontSize: width(3.7),
    maxWidth: width(35)
  },
  shopNamePrice: {
    color: Colors.textBlack,
    fontSize: width(3.7),
  },
  comment: {
    color: Colors.textBlack,
    fontSize: width(3),
    marginVertical: height(1.5),
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  categoriesHeadingText: {
    color: Colors.gray,
    fontSize: width(2.7),
  },
  quantityText: {
    color: Colors.gray,
    fontSize: width(3.05),
    width: width(8),
    paddingRight: width(2),
  },
  itemPriceText: {
    color: Colors.textBlack,
    fontSize: width(3),
  },
  balHeadingText: {
    color: Colors.gray,
    fontSize: width(3.8),
  },
  categoriesText: {
    color: Colors.textBlack,
    fontWeight: 'bold',
    fontSize: width(3),
  },
  pricesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    margin: height(1),
    marginTop: 0,
    backgroundColor: '#f7f7f8',
    paddingVertical: height(2),
    borderBottomLeftRadius: width(4),
    borderBottomRightRadius: width(4),
  },
  verticleLine: {
    width: 1,
    height: '90%',
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  priceText: {
    color: Colors.textBlack,
    fontSize: width(4),
  },
  acceptanceContainer: {
    width: width(80),
    alignSelf: 'center',
    alignItems:'center',
    paddingVertical: height(2),
    borderBottomRightRadius: width(7),
    borderBottomLeftRadius: width(7),
  },
  acceptanceText: {
    color: Colors.purplePrimary,
    fontSize: width(3),
    fontWeight: 'bold',
    paddingHorizontal: width(2),
    textAlign:'center'
  },
  clientDetailsContainer: {
    width: width(90),
    borderRadius: width(4),
    backgroundColor: Colors.backgroundWhite,
    alignSelf: 'center',
    marginTop: height(2.5),
    paddingTop: height(1.5),
  },
  heading: {
    paddingHorizontal: width(5),
    paddingVertical: height(1.3),
    fontWeight: 'bold',
    color: Colors.textBlack,
    fontSize: width(3.6),
  },
  clientheading: {
    paddingLeft: width(5),
    paddingVertical: height(1.3),
    color: Colors.textBlack,
    fontSize: width(3.6),
  },
  clientDataContainer: {
    width: width(80),
    alignSelf: 'center',
  },
  clientImage: {
    height: height(8),
    width: height(8),
    borderRadius: height(4),
  },
  nameContainer: {
    marginHorizontal: width(7),
    paddingTop: height(1),
  },
  clientName: {
    fontWeight: 'bold',
    fontSize: width(4.3),
  },
  clientText: {
    color: Colors.buttonBlue,
    fontSize: width(3.4),
  },
  paymentMethodsHeadingText: {
    color: Colors.textBlack,
    fontWeight: 'bold',
    fontSize: width(5),
    paddingLeft: width(5),
    paddingVertical: height(3),
  },
  walletContainer: {
    width: width(90),
    borderRadius: width(4),
    backgroundColor: Colors.backgroundWhite,
    alignSelf: 'center',
    marginTop: height(1),
    paddingBottom: height(1.25),
    paddingTop: height(1.25),
    paddingHorizontal: width(4),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: height(2),
  },
  walletButtonContainer: {
    height: totalSize(5),
    width: totalSize(5),
    borderRadius: totalSize(1),
    backgroundColor: Colors.opacitiveBlue,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: width(4),
  },
  addMethodButton: {
    paddingHorizontal: width(5),
    paddingVertical: height(0.5),
    borderRadius: width(5),
    backgroundColor: Colors.buttonBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: width(2),
  },
  addMethodButtonText: {
    color: Colors.backgroundWhite,
    fontSize: width(3.5),
  },
  topContainer: {
    width: width(100),
    paddingBottom: height(4),
    borderBottomLeftRadius: width(7),
    borderBottomRightRadius: width(7),
    backgroundColor: Colors.backgroundWhite,
  },
  idCont: {
    paddingHorizontal: width(5),
    width: width(100),
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: height(2),
  },
  id: { color: Colors.lightGray, fontSize: width(4) },
  idText: { color: Colors.textBlack, fontSize: width(3.5) },
  labelCont: {
    paddingHorizontal: width(5),
    width: width(100),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: height(2),
  },
  label: { color: Colors.textBlack, fontSize: width(6), fontWeight: 'bold' },
  dispCont: { flexDirection: 'row', marginTop: height(2) },
  locationImg: {
    width: width(4),
    height: width(5),
    marginTop: height(0.5),
    resizeMode: 'contain',
  },
  adress: {
    color: Colors.textBlack,
    marginHorizontal: width(1.5),
    fontSize: width(3.5),
    width: width(45),
  },
  adress1: {
    color: Colors.textBlack,
    marginLeft: width(3),
    fontSize: width(4),
    width: width(45),
  },
  home: {
    color: Colors.textBlack,
    fontSize: width(4),
    marginTop: height(1),
  },
  adress2: {
    color: Colors.textBlack,
    fontSize: width(2.8),
    width: '100%',
    marginTop: height(0.8),
    opacity: 0.7,
  },
  backImg: { width: '100%', height: '100%', borderRadius: width(5) },
  backgroundImg: {
    width: width(90),
    height: height(25),
    marginVertical: height(4),
    alignSelf: 'center',
    elevation: 10,
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: width(5),
  },
  imgCont: { flexDirection: 'row', alignSelf: 'center', alignItems: 'center' },
  line: { width: width(10), height: 1.8, backgroundColor: Colors.black },
  orderCont: {
    paddingVertical: height(1),
    paddingHorizontal: width(5),
    borderRadius: width(7),
    backgroundColor: Colors.black,
  },
  completed: { color: Colors.backgroundWhite, fontSize: width(4.5) },
  time: {
    color: '#1C2D41',
    fontSize: width(4),
    textAlign: 'center',
    marginTop: height(3),
    opacity: 0.5,
  },
  count: {
    width: '34%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  accepted: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: height(0.6),
  },
  deleveryBy: {
    width: width(1),
    height: width(1),
    borderRadius: width(1),
    backgroundColor: Colors.buttonBlue,
    marginHorizontal: width(1),
  },
  adressCont: {
    width: '90%',
    alignSelf: 'center',
    marginTop: height(2),
    marginBottom: height(3.5),
    backgroundColor: '#f7f7f8',
    paddingHorizontal: '5%',
    paddingVertical: height(2),
    borderRadius: width(4),
  },
  locationCont: {
    flexDirection: 'row',
     alignItems: 'center',
  },
  reviewConainer:{
    width: '90%',
    justifyContent:'space-between'
  },
  rateOrder:{
    color: Colors.buttonBlue,
    fontSize: width(3.3),
    textAlign:'center',
    alignSelf:'center'
  },
});
export default styles;
