export default [
    {
        id: 'OR5456UIS432',
        dateTime: '9:30 AM, 18 Apr,2020',
        storeName: 'Sofia Retailer Store',
        image: 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
        price: '200',
        items: '3 Items Purchased',
        key: 1,
        name: 'Jeson Wolf',
        orderId: 'OR4569EB320',
        price: 210.0,
        timeLeft: '1 day,18 hours',
        deliveryDateTime: '09:30 PM 18 Apr,2020',
        selfPickup: true,
        providerDelivery: false,
        storeImage:
          'https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
        isHidden: 'true',
        Address: 'C-404, Golden Street, East 25th Street, New york City, US',
        // providerBy: {
          deliverBy: 'Driver',
          providerName: 'julia Doe',
          providerImage: require('../assets/HomeAssets/Layer861copy.png'),
          providerPrice: 15,
          userType: 'provider',
        // },
        // client: {
          clientName: 'Martin Goe',
          clientImage: require('../assets/HomeAssets/Layer755.png'),
          clientPrice: 45,
          userType: 'client',
        // },
        itemList: [
          {
            key: 0,
            itemname: 'Salted chocolate cookie',
            itemId: 5623146,
            itemPrice: 140,
            comment: 'With Extra Bags',
            shortDescription: 'Extra chess and Extra with honey',
            quantity: 1,
            itemimage: [
              require('../assets/HomeAssets/Layer888copy2.png'),
              require('../assets/HomeAssets/Layer928.png'),
              require('../assets/HomeAssets/Layer935.png'),
            ],
            tags: ['Thaifood', 'Spicy'],
            description:
              'Lorem Ipsum is simply dummied text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
          },
          {
            key: 1,
            itemname: 'Coko Cookies',
            itemPrice: 140,
            itemId: 5623120,
            quantity: 2,
            comment: 'With Extra Sugar',
            shortDescription: 'Extra chess and Extra...',
            itemimage: [
              require('../assets/HomeAssets/Layer889copy2.png'),
              require('../assets/HomeAssets/Layer889copy2.png'),
              require('../assets/HomeAssets/Layer889copy2.png'),
            ],
            tags: ['Thaifood', 'Spicy'],
            description:
              'Lorem Ipsum is simply dummied text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
          },
        ],
    },
    {
        id: 'OR5456UIS433',
        dateTime: '9:30 AM, 18 Apr,2020',
        storeName: 'Sweethouse Store',
        image: 'https://images.unsplash.com/photo-1583823062258-f57312ee7ea1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
        price: '320',
        items: '2 Items Purchased',
        key: 1,
        name: 'Jeson Wolf',
        orderId: 'OR4569EB320',
        price: 210.0,
        timeLeft: '1 day,18 hours',
        deliveryDateTime: '09:30 PM 18 Apr,2020',
        selfPickup: false,
        providerDelivery: false,
        storeImage:
          'https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
        isHidden: 'true',
        Address: 'C-404, Golden Street, East 25th Street, New york City, US',
        // providerBy: {
          deliverBy: 'Driver',
          providerName: 'julia Doe',
          providerImage: require('../assets/HomeAssets/Layer861copy.png'),
          providerPrice: 15,
          userType: 'provider',
        // },
        // client: {
          clientName: 'Martin Goe',
          clientImage: require('../assets/HomeAssets/Layer755.png'),
          clientPrice: 45,
          userType: 'client',
        // },
        itemList: [
          {
            key: 0,
            itemname: 'Salted chocolate cookie',
            itemId: 5623146,
            itemPrice: 140,
            comment: 'With Extra Bags',
            shortDescription: 'Extra chess and Extra with honey',
            quantity: 1,
            itemimage: [
              require('../assets/HomeAssets/Layer888copy2.png'),
              require('../assets/HomeAssets/Layer928.png'),
              require('../assets/HomeAssets/Layer935.png'),
            ],
            tags: ['Thaifood', 'Spicy'],
            description:
              'Lorem Ipsum is simply dummied text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
          },
          {
            key: 1,
            itemname: 'Coko Cookies',
            itemPrice: 140,
            itemId: 5623120,
            quantity: 2,
            comment: 'With Extra Sugar',
            shortDescription: 'Extra chess and Extra...',
            itemimage: [
              require('../assets/HomeAssets/Layer889copy2.png'),
              require('../assets/HomeAssets/Layer889copy2.png'),
              require('../assets/HomeAssets/Layer889copy2.png'),
            ],
            tags: ['Thaifood', 'Spicy'],
            description:
              'Lorem Ipsum is simply dummied text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
          },
        ],
    },
    {
        id: 'OR5456UIS434',
        dateTime: '9:30 AM, 18 Apr,2020',
        storeName: 'Jac & J Salon',
        image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
        price: '200',
        items: '1 Service purchased',
        key: 1,
        name: 'Jeson Wolf',
        orderId: 'OR4569EB320',
        price: 210.0,
        timeLeft: '1 day,18 hours',
        deliveryDateTime: '09:30 PM 18 Apr,2020',
        selfPickup: false,
        providerDelivery: true,
        storeImage:
          'https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
        isHidden: 'true',
        Address: 'C-404, Golden Street, East 25th Street, New york City, US',
        // providerBy: {
          deliverBy: 'Driver',
          providerName: 'julia Doe',
          providerImage: require('../assets/HomeAssets/Layer861copy.png'),
          providerPrice: 15,
          userType: 'provider',
        // },
        // client: {
          clientName: 'Martin Goe',
          clientImage: require('../assets/HomeAssets/Layer755.png'),
          clientPrice: 45,
          userType: 'client',
        // },
        itemList: [
          {
            key: 0,
            itemname: 'Salted chocolate cookie',
            itemId: 5623146,
            itemPrice: 140,
            comment: 'With Extra Bags',
            shortDescription: 'Extra chess and Extra with honey',
            quantity: 1,
            itemimage: [
              require('../assets/HomeAssets/Layer888copy2.png'),
              require('../assets/HomeAssets/Layer928.png'),
              require('../assets/HomeAssets/Layer935.png'),
            ],
            tags: ['Thaifood', 'Spicy'],
            description:
              'Lorem Ipsum is simply dummied text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
          },
          {
            key: 1,
            itemname: 'Coko Cookies',
            itemPrice: 140,
            itemId: 5623120,
            quantity: 2,
            comment: 'With Extra Sugar',
            shortDescription: 'Extra chess and Extra...',
            itemimage: [
              require('../assets/HomeAssets/Layer889copy2.png'),
              require('../assets/HomeAssets/Layer889copy2.png'),
              require('../assets/HomeAssets/Layer889copy2.png'),
            ],
            tags: ['Thaifood', 'Spicy'],
            description:
              'Lorem Ipsum is simply dummied text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
          },
        ],
    },
]