export default approvedOrders = [
    {
        key: 1,
        OrderId:'ORD260RT5640',
        DeliveryTime:'08:00 AM, Mar 23,2020',
        ProviderAddress:'C-40, Golden Street, East 6th Street, New York,USA',
        BuyerAddress:'C-40, Golden Street, East 6th Street, New York,USA',
        DeliveryCharges:25,
        ServiceFees:5,
        status:'pending',
        providerName:'Robin Jeans',
        providerImage:require('../assets/DriverHome/Layer30.png'),
        clientName:'Mike Wheeler',
        clientImage:require('../assets/DriverHome/Layer531.png'),
        totalPackage:1,
        amountStatus:'Paid',
        notefromUser:'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available.'
    },
    {
        key: 2,
        OrderId:'ORD260RT5640',
        DeliveryTime:'08:00 AM, Mar 23,2020',
        ProviderAddress:'C-40, Golden Street, East 6th Street, New York,USA',
        BuyerAddress:'C-40, Golden Street, East 6th Street, New York,USA',
        DeliveryCharges:25,
        ServiceFees:5,
        status:'pending',
        providerName:'Robin Jeans',
        providerImage:require('../assets/DriverHome/Layer30.png'),
        clientName:'Mike Wheeler',
        clientImage:require('../assets/DriverHome/Layer531.png'),
        totalPackage:1,
        amountStatus:'Paid',
    },
    {
        key: 3,
        OrderId:'ORD260RT56405',
        DeliveryTime:'08:00 AM, Mar 23,2020',
        ProviderAddress:'C-40, Golden Street, East 6th Street, New York,USA',
        BuyerAddress:'C-40, Golden Street, East 6th Street, New York,USA',
        DeliveryCharges:25,
        ServiceFees:5,
        status:'Accepted',
        providerName:'Robin Jeans',
        providerImage:require('../assets/DriverHome/Layer30.png'),
        clientName:'Mike Wheeler',
        clientImage:require('../assets/DriverHome/Layer531.png'),
        totalPackage:1,
        amountStatus:'Paid',
        notefromUser:'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available.'
    },
    {
        key: 4,
        OrderId:'ORD260RT56405',
        DeliveryTime:'08:00 AM, Mar 23,2020',
        ProviderAddress:'C-40, Golden Street, East 6th Street, New York,USA',
        BuyerAddress:'C-40, Golden Street, East 6th Street, New York,USA',
        DeliveryCharges:25,
        ServiceFees:5,
        status:'Accepted',
        providerName:'Robin Jeans',
        providerImage:require('../assets/DriverHome/Layer30.png'),
        clientName:'Mike Wheeler',
        clientImage:require('../assets/DriverHome/Layer531.png'),
        totalPackage:1,
        amountStatus:'Paid'
    },
]