// Auth types
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SETBUYER = 'SETBUYER';
export const SETPROVIDER = 'SETPROVIDER';
export const SETDRIVER = 'SETDRIVER';
export const SETLANGUAGE = 'SETLANGUAGE';
export const SETCURRENCY = 'SETCURRENCY';
export const SETDISTANCEUNIT = 'SETDISTANCEUNIT';
export const SETRADIUS = 'SETRADIUS';
export const DRIVERLOGIN = 'DRIVERLOGIN';
export const PROVIDERLOGIN = 'PROVIDERLOGIN';
export const ORDERSTATUS = 'ORDERSTATUS';
// Store types
export const SETITEM = 'SETITEM';
export const PROFILECOMPLETE = 'PROFILECOMPLETE';
export const SETSTORECREATED = 'SETSTORECREATED';
export const SETPROVIDERSFILTER = 'SETPROVIDERSFILTER';